### ISSUE TITLE
Prototype

### ISSUE THREAD

**Issue by h-mathias** [csak4954/SEPM#13]
Create a runnable Model/Controller prototype

**Comment by f-tischler** [comment]
Der develop Zweig beinhaltet einen ersten Entwurf des Domain-Models als Klassendiagramm (doc/design/model/domain_model_class_dgram). Dieser ist bei weitem noch nicht vollständig und wird im Laufe des Projekts noch erweitert. 

Falls es keine Einwände gibt werde ich das DataStorage-Modul und das Authorization-Modul diese Woche partiell implementieren (für die Funktionalität des geforderten Prototypes).

@csaq9787 überleg dir bitte was das DataManipulation- und das DataEvaluation-Modul für Services anbieten soll und versuch grob die Modulstruktur festzulegen (ähnlich wie bei den anderen Modulen). Bitte noch nichts ausimplementieren! Wenn du fertig bist, pushe dein Diagramm nach develop damit ich es mir ansehen kann.

Bei Fragen bitte Telegram nutzen (je nach dem als Gruppennachricht oder PN)

**Comment by f-tischler** [comment]
@csaq9787 da ich bis jetzt nichts von dir gehört habe, nehme ich an das du nichts gemacht hast und werde das nun selber machen damit wir rechtzeitig fertig werden

**Comment by f-tischler** [comment]
@Zwingling hat den data manipulation layer übernommen

**Comment by f-tischler** [comment]
@csaq9787 bitte überleg dir was das DataEvaluation-Modul alles machen muss und welche Services es nutzt bzw. bereitstellt. Erstelle ein Klassendiagramm, commit es auf develop und meld dich dann noch einmal damit ich mir deinen Entwurf anschauen kann und meine Module anpassen kann

Bei Fragen bitte auf Telegram melden

**Comment by f-tischler** [comment]
@csaq9787 wenn bis morgen keine Resultate vorliegen, werde ich dich beim Proseminarleiter melden da du bis dato nichts zum Projekt beigetragen hast. Ich habe mit dir beim letzten Proseminar gesprochen und dir deutlich gemacht, dass es so nicht weitergehen kann. Weiters habe ich dir mehrmals angeboten mich zu kontaktieren falls du Probleme mit der Aufgabenstellung hast. Daher muss ich davon ausgehen, dass dich das Projekt nicht interessiert bzw. du nicht genug Zeit hast um mitzuarbeiten.

**Comment by f-tischler** [comment]
Prototyp eigentlich komplett. Module auf  #19 #20 #21 #22 verlagert
