### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by h-mathias** [csak4954/SEPM#14]
set up CI service

**Comment by f-tischler** [comment]
@csak4954 das kann nur der repository owner machen -> hier der link: https://travis-ci.org/

**Comment by csak4954** [comment]
travis-ci mit SEPM verbunden
next step: travis sagen was zu tun ist (.travis.yml zum repo hinzufuegen)

**Comment by csak4954** [comment]
done whats possible so far (connection and offline-setup). 
next step: the repo only can be build if our source isnt hidden behind folders. 
(im repo-root muss die .build.gradle etc vorhanden sein ...
vorschlag: source einmal in den master pushen, dann kann ich ci darauf konfigurieren)

**Comment by f-tischler** [comment]
problem ist, dass wir gradle per hand konfigurieren müssen da die STS mit gradle nicht einwandfrei zusammenarbeitet. Wir müssen vorerst bei maven bleiben da das Projekt nicht mehr auf den Tomcat deployed werden kann

**Comment by f-tischler** [comment]
@csak4954 hab die .travis.yml datei hinzugefügt. Kannst du den CI Service nicht für den "develop" Zweig konfigurieren?

**Comment by f-tischler** [comment]
@csak4954 hat sich erledigt

CI funktioniert jetzt https://travis-ci.org/csak4954/SEPM/builds/58116352
