### ISSUE TITLE
Thymeleaf

### ISSUE THREAD

**Issue by f-tischler** [csak4954/SEPM#16]
Hast du dir das schon angeschaut?

**Comment by csak4954** [comment]
alter, nicht stressen.
komme gerade aus vbg- war meinen bambino besuchen.
melde mich jetzt zum telegram an-  das ist ein colles ding.
mal schauen.
morgen schaue ich mir an, was ihr bereits gemacht habt,
und gehe meinen teil an.
c u @ telegram

Zitat von Florian notifications@github.com:

**Comment by f-tischler** [comment]
@Zwingling  dann brauchen wir Thymeleaf eher nicht oder? Wenn nicht bitte Issue schließen
