### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by f-tischler** [csak4954/SEPM#18]
Implementierung der REST API

**Comment by f-tischler** [comment]
@csak4954  hier das Tutorial: http://www.mkyong.com/spring-mvc/spring-3-mvc-and-json-example/

**Comment by csak4954** [comment]
@Zwingling 
du kannst in deinen views bereits testen wie du mit den json-objekten umgehen musst. 
als beispiel: 
http://localhost:8080/los/professor/{id} 
-> wobei im moment die id nicht stimmen muss, weil unser mock nur einen professor hat
die anfrage liefert das objekt (wie es im mock angegeben ist) als json: 
{"name":"florian","surname":"tischler","email":"(floriansEmail)","id":123456789,"affilation":"staff"}

**Comment by csak4954** [comment]
die REST-API habe ich in der README angelegt, 
und wird in den folgetagen erweitert....

**Comment by csak4954** [comment]
now workable version with spring-core4 in developer
