### ISSUE TITLE
Controller Implementation

### ISSUE THREAD

**Issue by csak4954** [csak4954/SEPM#29]
continue building and replacing mocks

**Comment by f-tischler** [comment]
nicht vergessen entweder die mongo db installieren oder eine neue konfiguration machen mit fake mongo (siehe model unit test konfiguration)...wenns probleme gibt bitte committen dann schau ichs mir an

http://docs.mongodb.org/manual/installation/

**Comment by f-tischler** [comment]
updated with 3d902b201c5943d9d52933d8522f375a270491f3

@Zwingling View Tests können starten
